import yaml
from pathlib import Path

BASE_DIR = Path(__file__).parent
LOCALES_DIR = BASE_DIR / "locales"
OUTPUT_FILE = BASE_DIR / "js" / "i18n.js"

def load_locale(lang: str) -> dict:
    """Load all YAML files for a language into a single dict."""
    locale_data = {}
    lang_dir = LOCALES_DIR / lang
    if not lang_dir.exists():
        return locale_data
    
    for yaml_file in sorted(lang_dir.glob("*.yaml")):
        with open(yaml_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            if data:
                locale_data.update(data)
    
    return locale_data

def generate_js():
    """Generate i18n.js with all locale data embedded."""
    locales = {}
    for lang_dir in sorted(LOCALES_DIR.iterdir()):
        if lang_dir.is_dir():
            lang = lang_dir.name
            locales[lang] = load_locale(lang)

    js_content = f"""// Auto-generated by build.py - do not edit manually
const I18N = {repr(locales)};
const DEFAULT_LANG = 'en';

function getBrowserLang() {{
    const lang = (navigator.language || 'en').toLowerCase();
    for (const key of Object.keys(I18N)) {{
        if (lang.startsWith(key)) return key;
    }}
    return DEFAULT_LANG;
}}

let currentLang = localStorage.getItem('lang') || getBrowserLang();

function t(key) {{
    const langData = I18N[currentLang] || I18N[DEFAULT_LANG];
    return langData[key] || I18N[DEFAULT_LANG][key] || key;
}}

function setLang(lang) {{
    if (I18N[lang]) {{
        currentLang = lang;
        localStorage.setItem('lang', lang);
        document.documentElement.lang = lang;
        applyTranslations();
    }}
}}

function applyTranslations() {{
    for (const [id, text] of Object.entries(I18N[currentLang])) {{
        const el = document.getElementById(id);
        if (el) {{
            el.innerHTML = text;
        }}
    }}
    document.dispatchEvent(new CustomEvent('i18n:changed', {{ detail: {{ lang: currentLang }} }}));
}}

document.addEventListener('DOMContentLoaded', applyTranslations);
"""

    OUTPUT_FILE.write_text(js_content, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE} with languages: {', '.join(locales.keys())}")

if __name__ == "__main__":
    generate_js()
