import json
import sys

import yaml
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

BASE_DIR = Path(__file__).parent
LOCALES_DIR = BASE_DIR / "locales"
# Generated data lives under dist/ so build output, gitignore and the size
# ratchet share one list instead of a per-file list that rots.
DIST_DIR = BASE_DIR / "dist"
DIST_JS_DIR = DIST_DIR / "js"
OUTPUT_FILE = DIST_JS_DIR / "translations.js"
TEMPLATES_DIR = BASE_DIR / "templates"
OUTPUT_HTML = BASE_DIR / "index.html"
CONTENT_DIR = BASE_DIR / "content"
JS_DIR = BASE_DIR / "js"

def load_locale(lang: str) -> dict:
    """Load all YAML files for a language into a single dict."""
    locale_data = {}
    lang_dir = LOCALES_DIR / lang
    if not lang_dir.exists():
        return locale_data
    
    for yaml_file in sorted(lang_dir.glob("*.yaml")):
        with open(yaml_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            if data:
                locale_data.update(data)
    
    return locale_data

def load_changelog() -> list:
    """Load the shared changelog (en/ru inside) as a list of dicts."""
    changelog_file = LOCALES_DIR / "changelog.yaml"
    if not changelog_file.exists():
        return []
    with open(changelog_file, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or []

def generate_js():
    """Generate i18n.js with all locale data embedded."""
    locales = {}
    for lang_dir in sorted(LOCALES_DIR.iterdir()):
        if lang_dir.is_dir():
            lang = lang_dir.name
            locales[lang] = load_locale(lang)

    changelog = load_changelog()

    js_content = f"""// Auto-generated by build.py - do not edit manually
const I18N = {repr(locales)};
const CHANGELOG = {repr(changelog)};
const DEFAULT_LANG = 'en';

function getBrowserLang() {{
    const lang = (navigator.language || 'en').toLowerCase();
    for (const key of Object.keys(I18N)) {{
        if (lang.startsWith(key)) return key;
    }}
    return DEFAULT_LANG;
}}

let currentLang = localStorage.getItem('lang') || getBrowserLang();

function t(key, ...args) {{
    const langData = I18N[currentLang] || I18N[DEFAULT_LANG];
    let text = langData[key] || I18N[DEFAULT_LANG][key] || key;
    args.forEach((arg, i) => {{
        text = text.replaceAll('{{' + i + '}}', String(arg));
    }});
    return text;
}}

function setLang(lang) {{
    if (I18N[lang]) {{
        currentLang = lang;
        localStorage.setItem('lang', lang);
        document.documentElement.lang = lang;
        applyTranslations();
    }}
}}

function applyTranslations() {{
    for (const [id, text] of Object.entries(I18N[currentLang])) {{
        const el = document.getElementById(id);
        if (el) {{
            el.innerHTML = text;
        }}
    }}
    document.dispatchEvent(new CustomEvent('i18n:changed', {{ detail: {{ lang: currentLang }} }}));
}}

document.addEventListener('DOMContentLoaded', applyTranslations);
"""

    DIST_JS_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(js_content, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE} with languages: {', '.join(locales.keys())}")
    return locales

def generate_html():
    """Render index.html from Jinja2 templates."""
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)), autoescape=False)
    template = env.get_template("index.html")
    html = template.render()
    OUTPUT_HTML.write_text(html, encoding="utf-8")
    print(f"Generated {OUTPUT_HTML}")
    return html


def generate_data_files():
    """Generate dist/js/*_data.js from content/*.json. Top-level keys become consts."""
    DIST_JS_DIR.mkdir(parents=True, exist_ok=True)
    for json_file in sorted(CONTENT_DIR.glob("*.json")):
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        lines = ["// Auto-generated by build.py - do not edit manually"]
        # Категорийные контейнеры. Два формата:
        #   unified:  { "<category_id>": { "name": "<locale_key>", "items": {...} } }
        #   legacy:   { "<category_name>": { "<entity_id>": {...} } }
        # Файл, перенесённый на id-ключи, переходит на unified; legacy-файлы ещё работают.
        container_name = next((k for k in data if k.endswith("Categories")), None)
        if container_name is not None:
            entity_prefix = container_name.replace("Categories", "").lower()
            categories_container = data[container_name]
            unified = all(isinstance(c, dict) and "items" in c for c in categories_container.values())
            lines.append(f"const {container_name} = {json.dumps(categories_container, ensure_ascii=False)};")
            if unified:
                lines.append(f"const {entity_prefix}BaseData = Object.assign({{}}, ...Object.values({container_name}).map(c => c.items));")
            else:
                lines.append(f"const {entity_prefix}BaseData = Object.assign({{}}, ...Object.values({container_name}));")
        else:
            for key, value in data.items():
                lines.append(f"const {key} = {json.dumps(value, ensure_ascii=False)};")
        out = DIST_JS_DIR / (json_file.stem + "_data.js")
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Generated {out}")


def load_entity_names():
    """Extract category keys and content entity ids with their translation keys."""
    categories = set()
    content = {}
    entity_meta = {}  # stem -> {entity_id: {"name": key, "desc": key, "tooltip": key}}
    for json_file in sorted(CONTENT_DIR.glob("*.json")):
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        container_name = next((k for k in data if k.endswith("Categories")), None)
        if container_name is None:
            continue
        stem = json_file.stem
        for category_id, category in data[container_name].items():
            if not (isinstance(category, dict) and "items" in category):
                continue
            categories.add(category["name"])
            content.setdefault(stem, set()).update(category["items"].keys())
            for entity_id, entity in category["items"].items():
                entity_meta.setdefault(stem, {})[entity_id] = {
                    "name": entity.get("name"),
                    "desc": entity.get("description"),
                    "tooltip": entity.get("tooltip"),
                }
    return categories, content, entity_meta


def validate(locales: dict, errors=None):
    """Fail the build on missing translations.

    Only this: keys that are absent would be caught anyway, but ~180 entities x
    two languages is a thousand checks nobody does by hand, and the game hides
    most of them behind progress. Checks that only fire on a typo in getElementById
    were removed — such a typo blanks the whole tab the moment it is opened,
    which is louder and faster than a build failure.
    """
    if errors is None:
        errors = []
    categories, content, entity_meta = load_entity_names()
    for lang, keys in locales.items():
        missing_names = sorted(n for n in categories if n not in keys)
        if missing_names:
            errors.append(f"[{lang}] Names missing translation: {missing_names}")
        for stem, entity_ids in content.items():
            meta = entity_meta.get(stem, {})
            for entity_id in sorted(entity_ids):
                m = meta.get(entity_id, {})
                for field in ("name", "desc", "tooltip"):
                    key = m.get(field)
                    if key and key not in keys:
                        errors.append(f"[{lang}] Missing {key} translation")

    if errors:
        print("\n=== BUILD VALIDATION FAILED ===", file=sys.stderr)
        for err in errors:
            print(" -", err, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    generate_data_files()
    locales = generate_js()
    generate_html()
    validate(locales)
