import json
import re
import sys
from collections import Counter

import yaml
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

BASE_DIR = Path(__file__).parent
LOCALES_DIR = BASE_DIR / "locales"
OUTPUT_FILE = BASE_DIR / "js" / "translations.js"
TEMPLATES_DIR = BASE_DIR / "templates"
OUTPUT_HTML = BASE_DIR / "index.html"
CONTENT_DIR = BASE_DIR / "content"
JS_DIR = BASE_DIR / "js"

def load_locale(lang: str) -> dict:
    """Load all YAML files for a language into a single dict."""
    locale_data = {}
    lang_dir = LOCALES_DIR / lang
    if not lang_dir.exists():
        return locale_data
    
    for yaml_file in sorted(lang_dir.glob("*.yaml")):
        with open(yaml_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            if data:
                locale_data.update(data)
    
    return locale_data

def load_changelog() -> list:
    """Load the shared changelog (en/ru inside) as a list of dicts."""
    changelog_file = LOCALES_DIR / "changelog.yaml"
    if not changelog_file.exists():
        return []
    with open(changelog_file, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or []

def generate_js():
    """Generate i18n.js with all locale data embedded."""
    locales = {}
    for lang_dir in sorted(LOCALES_DIR.iterdir()):
        if lang_dir.is_dir():
            lang = lang_dir.name
            locales[lang] = load_locale(lang)

    changelog = load_changelog()

    js_content = f"""// Auto-generated by build.py - do not edit manually
const I18N = {repr(locales)};
const CHANGELOG = {repr(changelog)};
const DEFAULT_LANG = 'en';

function getBrowserLang() {{
    const lang = (navigator.language || 'en').toLowerCase();
    for (const key of Object.keys(I18N)) {{
        if (lang.startsWith(key)) return key;
    }}
    return DEFAULT_LANG;
}}

let currentLang = localStorage.getItem('lang') || getBrowserLang();

function t(key, ...args) {{
    const langData = I18N[currentLang] || I18N[DEFAULT_LANG];
    let text = langData[key] || I18N[DEFAULT_LANG][key] || key;
    args.forEach((arg, i) => {{
        text = text.replaceAll('{{' + i + '}}', String(arg));
    }});
    return text;
}}

function setLang(lang) {{
    if (I18N[lang]) {{
        currentLang = lang;
        localStorage.setItem('lang', lang);
        document.documentElement.lang = lang;
        applyTranslations();
    }}
}}

function applyTranslations() {{
    for (const [id, text] of Object.entries(I18N[currentLang])) {{
        const el = document.getElementById(id);
        if (el) {{
            el.innerHTML = text;
        }}
    }}
    document.dispatchEvent(new CustomEvent('i18n:changed', {{ detail: {{ lang: currentLang }} }}));
}}

document.addEventListener('DOMContentLoaded', applyTranslations);
"""

    OUTPUT_FILE.write_text(js_content, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE} with languages: {', '.join(locales.keys())}")
    return locales

def generate_html():
    """Render index.html from Jinja2 templates."""
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)), autoescape=False)
    template = env.get_template("index.html")
    html = template.render()
    OUTPUT_HTML.write_text(html, encoding="utf-8")
    print(f"Generated {OUTPUT_HTML}")
    return html


def generate_data_files():
    """Generate js/*_data.js from content/*.json. Top-level keys become consts."""
    for json_file in sorted(CONTENT_DIR.glob("*.json")):
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        lines = ["// Auto-generated by build.py - do not edit manually"]
        # Категорийные контейнеры. Два формата:
        #   unified:  { "<category_id>": { "name": "<locale_key>", "items": {...} } }
        #   legacy:   { "<category_name>": { "<entity_id>": {...} } }
        # Файл, перенесённый на id-ключи, переходит на unified; legacy-файлы ещё работают.
        container_name = next((k for k in data if k.endswith("Categories")), None)
        if container_name is not None:
            entity_prefix = container_name.replace("Categories", "").lower()
            categories_container = data[container_name]
            unified = all(isinstance(c, dict) and "items" in c for c in categories_container.values())
            lines.append(f"const {container_name} = {json.dumps(categories_container, ensure_ascii=False)};")
            if unified:
                lines.append(f"const {entity_prefix}BaseData = Object.assign({{}}, ...Object.values({container_name}).map(c => c.items));")
            else:
                lines.append(f"const {entity_prefix}BaseData = Object.assign({{}}, ...Object.values({container_name}));")
        else:
            for key, value in data.items():
                lines.append(f"const {key} = {json.dumps(value, ensure_ascii=False)};")
        out = JS_DIR / (json_file.stem + "_data.js")
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Generated {out}")


def load_entity_names():
    """Extract legacy entity names, content entity ids and category keys from data sources."""
    legacy, categories = set(), set()
    # Рукописные словари (работы и их категории) — имена остаются источником истины.
    src = (JS_DIR / "data.js").read_text(encoding="utf-8")
    legacy |= set(re.findall(r'\{ name: "([^"]+)",', src))
    categories |= set(re.findall(r'"([^"]+)":\s*\[', src))

    # Категорийные контейнеры из контента: id категорий и id сущностей.
    # unified-файлы (items) отдают id сущностей в .items; legacy-файлы (skills/milestones)
    # держат сущности прямо в категории. Вехи в legacy-формате проверяются по именам через legacy.
    content = {}
    unified_stems = set()
    entity_meta = {}  # stem -> {entity_id: {"name": key, "tooltip": key}}
    for json_file in sorted(CONTENT_DIR.glob("*.json")):
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        container_name = next((k for k in data if k.endswith("Categories")), None)
        if container_name is None:
            continue
        stem = json_file.stem
        for category_id, category in data[container_name].items():
            if isinstance(category, dict) and "items" in category:
                unified_stems.add(stem)
                categories.add(category["name"])
                entity_ids = category["items"].keys()
                for entity_id, entity in category["items"].items():
                    entity_meta.setdefault(stem, {})[entity_id] = {
                        "name": entity.get("name"),
                        "tooltip": entity.get("tooltip"),
                    }
            else:
                categories.add(category_id)
                if stem == "milestones":
                    for milestone in category.values():
                        legacy.add(milestone["name"])
                entity_ids = category.keys()
            content.setdefault(stem, set()).update(entity_ids)
    return legacy, content, categories, unified_stems, entity_meta


def validate(html: str, locales: dict, errors=None):
    """Fail the build on i18n/HTML regressions: missing ids, missing translations, duplicates."""
    if errors is None:
        errors = []
    js_src = ""
    for f in sorted(JS_DIR.glob("*.js")):
        if f.name in ("translations.js", "math.js", "HackTimer.js"):
            continue
        js_src += f.read_text(encoding="utf-8")

    html_ids = re.findall(r'id=["\']([^"\']+)["\']', html)
    dup_ids = {i for i, n in Counter(html_ids).items() if n > 1}
    if dup_ids:
        errors.append(f"Duplicate ids in HTML: {sorted(dup_ids)}")

    ids_used = set(re.findall(r'getElementById\("([^"]+)"\)', js_src))
    # ids created inside i18n strings (e.g. <span id="perkPointDisplay"> inside a translation)
    ids_in_i18n = set()
    for lang_keys in locales.values():
        for text in lang_keys.values():
            ids_in_i18n |= set(re.findall(r'id=["\']([^"\']+)["\']', text))
    missing = sorted((ids_used - ids_in_i18n) - set(html_ids))
    if missing:
        errors.append(f"JS references missing element ids: {missing}")

    legacy, content, categories, unified_stems, entity_meta = load_entity_names()
    names = legacy | categories
    for lang, keys in locales.items():
        missing_names = sorted(n for n in names if n not in keys)
        if missing_names:
            errors.append(f"[{lang}] Names missing translation: {missing_names}")
        missing_tt = sorted(n for n in legacy if ("tt_" + n) not in keys)
        if missing_tt:
            errors.append(f"[{lang}] Missing tt_ keys: {missing_tt}")
        for stem, entity_ids in content.items():
            if stem in ("items", "skills", "jobs"):
                meta = entity_meta.get(stem, {})
                for entity_id in sorted(entity_ids):
                    m = meta.get(entity_id, {})
                    name_key = m.get("name")
                    tooltip_key = m.get("tooltip")
                    if name_key and name_key not in keys:
                        errors.append(f"[{lang}] Missing {name_key} translation")
                    if tooltip_key and tooltip_key not in keys:
                        errors.append(f"[{lang}] Missing {tooltip_key} translation")
            elif stem == "milestones" and stem in unified_stems:
                for milestone_id in sorted(entity_ids):
                    if (milestone_id + "_name") not in keys:
                        errors.append(f"[{lang}] Missing {milestone_id}_name translation")
                    if (milestone_id + "_desc") not in keys:
                        errors.append(f"[{lang}] Missing {milestone_id}_desc translation")
                    if ("tt_" + milestone_id + "_name") not in keys:
                        errors.append(f"[{lang}] Missing tt_{milestone_id}_name translation")

    if errors:
        print("\n=== BUILD VALIDATION FAILED ===", file=sys.stderr)
        for err in errors:
            print(" -", err, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    generate_data_files()
    locales = generate_js()
    html = generate_html()
    validate(html, locales)
